name: Build and Release
on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
jobs:
    build-and-release:
      name: Build and Release
      runs-on: ubuntu-22.04
      timeout-minutes: 5
      environment: default
      env:
        REGISTRY_USERNAME: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
        REGISTRY_TOKEN: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
        COMPONENT_NAME: n8n-runner
      steps:
        - name: Checkout code
          uses: actions/checkout@v6

        - name: Dockerfile metadata
          id: dockerfile
          run: |
            VERSION=$(grep -oP '(?<=FROM n8nio/runners:)[^ ]+' Dockerfile)
            echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: |
              ${{ env.REGISTRY_USERNAME }}/${{ env.COMPONENT_NAME }}
            tags: |
              type=semver,pattern={{version}},value=${{ steps.dockerfile.outputs.version }}
              type=semver,pattern=v{{version}},value=${{ steps.dockerfile.outputs.version }}
              type=semver,pattern={{major}}.{{minor}},value=${{ steps.dockerfile.outputs.version }}
              type=semver,pattern=v{{major}}.{{minor}},value=${{ steps.dockerfile.outputs.version }}
              type=semver,pattern={{major}},value=${{ steps.dockerfile.outputs.version }}
              type=semver,pattern=v{{major}},value=${{ steps.dockerfile.outputs.version }}

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ env.REGISTRY_USERNAME }}
            password: ${{ env.REGISTRY_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
        